### ISSUE TITLE
Api mismatch 

### ISSUE THREAD

**Issue by mentoster** [mentoster/Flipper-hero#1]
The flipper shows this screen at the start. Need to fix.
![image](https://github.com/mentoster/Flipper-hero/assets/50594730/ab5962fa-252e-484e-832e-95b9bcbed1ec)

**Comment by theblackhole** [comment]
Just a little memo here after [our discussion on Reddit](https://www.reddit.com/r/flipperzero/comments/1blydyo/comment/kw89w5a/) :
- `ufbt update --branch=0.99.1` to build the app for the latest stable official firmware
- `ufbt update --branch=unlshd-071 --index-url=https://up.unleashedflip.com/directory.json` to build the app for the latest stable unleashed firmware (in theory, I haven't tried this one)
